[package]
name = "aptest"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
colored = "2.0.0"
ctrlc = "3.2.2"
yaml-rust = "0.4.5"
